src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Index(name: 'event', columns: ['nom_event', 'type_event'], flags: ['fulltext'])]

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    
    #[ORM\Id]

    #[ORM\Column(length: 255)]
    private ?string $nom_event = null;

    #[ORM\Column(length: 255)]
    private ?string $type_event = null;

    #[ORM\Column(length: 255)]
    private ?string $nbre_salle = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_deb = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column]
    private ?int $nbr_participants = null;

   

    public function getNomEvent(): ?string
    {
        return $this->nom_event;
    }

    public function setNomEvent(string $nom_event): self
    {
        $this->nom_event = $nom_event;

        return $this;
    }

    public function getTypeEvent(): ?string
    {
        return $this->type_event;
    }

    public function setTypeEvent(string $type_event): self
    {
        $this->type_event = $type_event;

        return $this;
    }

    public function getNbreSalle(): ?string
    {
        return $this->nbre_salle;
    }

    public function setNbreSalle(string $nbre_salle): self
    {
        $this->nbre_salle = $nbre_salle;

        return $this;
    }

    public function getDateDeb(): ?\DateTimeInterface
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTimeInterface $date_deb): self
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNbrParticipants(): ?int
    {
        return $this->nbr_participants;
    }

    public function setNbrParticipants(int $nbr_participants): self
    {
        $this->nbr_participants = $nbr_participants;

        return $this;
    }
}

src/Controller/PdfController.php
<?php
 
namespace App\Controller;
 
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Options;
use App\Entity\Event;


use App\Repository\DonRepository;
        
class PdfController extends AbstractController
{
  
    /**
     * @Route("/pdf", name="pdf")
     */
    public function pdf(EntityManagerInterface $em)
    {
        {
            $don=$em->getRepository(Event::class)->findAll();
            
    
            // On définit les options du PDF
            $pdfOptions = new Options();
            // Police par défaut
            $pdfOptions->set('defaultFont', 'Arial');
            $pdfOptions->setIsRemoteEnabled(true);
    
            // On instancie Dompdf
            $dompdf = new Dompdf($pdfOptions);
            
    
            // On génère le html
            $html = $this->renderView('pdf/index.html.twig',
                ['b'=>$don ]);
           
    //
    
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
    
            // On génère un nom de fichier
            $fichier = 'Tableau des dons.pdf';
    
            // On envoie le PDF au navigateur
            $dompdf->stream($fichier, [
                'Attachment' => true
            ]);
    
            return new Response();
        }
    }
 
   
   
}

templates/pdf/index.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Tableau des Events</title>
  </head>
  <body>
    <h2 style="text-align: center">Tableau des evenements</h2>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nom_event</th>
          <th>Type_event</th>
          <th>Nbre_salle</th>
          <th>Date_deb</th>
          <th>Date_fin</th>
          <th>Nbr_participants</th>
        </tr>
      </thead>
      <tbody>
        {% for event in b %}
        <tr>
          <td>{{ event.nomEvent }}</td>
          <td>{{ event.typeEvent }}</td>
          <td>{{ event.nbreSalle }}</td>
          <td>{{ event.dateDeb ? event.dateDeb|date('Y-m-d') : '' }}</td>
          <td>{{ event.dateFin ? event.dateFin|date('Y-m-d') : '' }}</td>
          <td>{{ event.nbrParticipants }}</td>
        </tr>
        {% else %}
        <tr>
          <td colspan="5">no records found</td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </body>
</html>